version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Compiling SCSS to CSS..."
      - npm run build  # This runs the build script in your package.json
  post_build:
    commands:
      - echo "Syncing compiled files to S3..."
      # Replace './dist' with your actual output folder name
      # Replace 'YOUR_BUCKET_NAME' with your actual S3 bucket name
      - aws s3 sync ./dist s3://auz-connect-recruitment-page --delete
